// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    return web;
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_apiKey'] ?? '',
    appId: dotenv.env['FIREBASE_appId'] ?? '',
    messagingSenderId: dotenv.env['FIREBASE_messagingSenderId'] ?? '',
    projectId: dotenv.env['FIREBASE_projectId'] ?? '',
    authDomain: dotenv.env['FIREBASE_authDomain'] ?? '',
    storageBucket: dotenv.env['FIREBASE_storageBucket'] ?? '',
    measurementId: dotenv.env['FIREBASE_measurementId'] ?? '',
  );
}
